ARG VERSION=latest
FROM rocm/pytorch:${VERSION}

# 更新包列表並安裝 OpenMPI
RUN apt-get update && apt-get install -y \
    cmake \
    # openmpi
    openmpi-bin openmpi-common libopenmpi-dev \
    # ASTRA-sim 需要的依賴
    libprotobuf-dev protobuf-compiler \
    libboost-dev libboost-program-options-dev \
    graphviz

# 設置 Horovod 環境變數
ENV HOROVOD_GPU=ROCM \
    HOROVOD_ROCM_HOME=/opt/rocm \
    HOROVOD_GPU_OPERATIONS=NCCL \
    HOROVOD_WITHOUT_TENSORFLOW=1 \
    HOROVOD_WITH_PYTORCH=1 \
    HOROVOD_WITH_MPI=1 \
    HOROVOD_WITHOUT_MXNET=1

# 安裝 Horovod 和其他依賴
RUN git clone --recursive https://github.com/horovod/horovod.git /workspace/horovod
RUN ln -s $ROCM_PATH/lib/cmake/hip/FindHIP* /workspace/horovod/cmake/Modules/
RUN sed -i 's/rccl\.h/rccl\/rccl\.h/' /workspace/horovod/horovod/common/ops/nccl_operations.h
RUN pip install --no-cache-dir /workspace/horovod/.

# Install Python protobuf package
RUN pip install protobuf==5.29.0

# 安裝 ASTRA-sim
ENV ASTRA_SIM="/workspace/astra-sim"
RUN git clone --recursive https://github.com/astra-sim/astra-sim.git ${ASTRA_SIM}
WORKDIR ${ASTRA_SIM}
RUN ./build/astra_analytical/build.sh
ENV ASTRA_SIM_BIN=${ASTRA_SIM}/build/astra_analytical/build/bin/AstraSim_Analytical_Congestion_Aware

# 編譯 astra-sim 的 ns3 模組
# C++ 20 引入了新的 fmt 庫，這可能會導致 ASTRA-sim 的一些舊程式無法編譯。
WORKDIR /workspace/astra-sim/extern/network_backend/ns-3
RUN git checkout astra-sim
WORKDIR /workspace/astra-sim/extern/helper/spdlog_setup
RUN sed -i 's/\bformat(/fmt::format(/g' conf.h details/conf_impl.h details/template_impl.h \
    && sed -i 's/fmt::fmt::format(/fmt::format(/g' conf.h details/conf_impl.h details/template_impl.h \
    && echo '#include <spdlog/fmt/fmt.h>' | cat - conf.h > temp && mv temp conf.h \
    && echo '#include <spdlog/fmt/fmt.h>' | cat - details/conf_impl.h > temp && mv temp details/conf_impl.h \
    && echo '#include <spdlog/fmt/fmt.h>' | cat - details/template_impl.h > temp && mv temp details/template_impl.h
WORKDIR ${ASTRA_SIM}
RUN ./build/astra_ns3/build.sh -c 2>&1 | tee /workspace/ns3_build_log.txt

# 安裝 Chakra (從 astra-sim fork)
# 修正 AMD GPU trace 無法被偵測的問題
RUN git clone https://github.com/astra-sim/chakra.git /workspace/chakra && \
    cd /workspace/chakra && \
    pip install --no-cache-dir .

# https://github.com/mlcommons/chakra/issues/195
RUN pip install protobuf==6.32.1

# 安裝其他 Chakra 依賴 Param
# REF https://github.com/mlcommons/chakra/blob/main/USER_GUIDE.md
# 安裝 PARAM (Chakra 依賴)
WORKDIR /workspace
RUN git clone https://github.com/facebookresearch/param.git && \
    cd param/et_replay && \
    git checkout 7b19f586dd8b267333114992833a0d7e0d601630 && \
    pip install .

# 安裝 Holistic Trace Analysis (用於追蹤分析)
WORKDIR /workspace
RUN git clone https://github.com/facebookresearch/HolisticTraceAnalysis.git && \
    cd HolisticTraceAnalysis && \
    git checkout v0.5.0 && \
    git submodule update --init && \
    pip install -r requirements.txt && \
    pip install -e .

RUN pip install hiredis --no-cache-dir

# 設置工作目錄
WORKDIR /workspace
